### PR TITLE
Added dependencies so that it's easier for more people to collaborate…

### PR DESCRIPTION
**Pull request by Swoot1**
… on the project and removed this reference and replaces it with bind. Also added the flag --debug in the package.json so that the .js files will be mapped to the sourcemap so that you don't have to debug the bundle.js file but can debug the actual .js files.

### CODE REVIEW

**Comment by krawaller** [comment]
:+1:

**Comment by as223jx** [comment]
Ah shoot! Somehow I didn't see this until now and I've made a lot of changes to the table-cell file, so I'm really not sure how to merge the .json file only. Help a noob out? :pray:

**Comment by krawaller** [comment]
@as223jx: If I remember correctly, there's a link right by the merge conflict notice that you can click for detailed instructions on how to handle that (it only shows for those with write access). This will allow you to solve the merge conflict locally. When that happens, all files with merge conflict will show both your changes and hers next to each other, and you can pick what to keep.

Another option is to smooch up to @Swoot1 and ask her to pull down your upstream changes to her fork, solve the merge conflicts and then push to her fork again.

**Comment by as223jx** [comment]
@krawaller Ah, I'll check that.. I'm still not very comfortable using GitHub so I'm worried I'll just somehow mess stuff up. :fearful: @Swoot1 Would be great if you'd be able to help out with the merge conflicts, no worries if not though!

**Comment by krawaller** [comment]
@as223jx: that's the beauty of version control - since we can always rewind in history if we find :hankey: in the repo, there's really no way you can mess stuff up! :)

**Comment by as223jx** [comment]
@krawaller True :point_up: I'll just have to try it out!

**Comment by Swoot1** [comment]
Hey! How's it going? Do you still need help?

**Comment by as223jx** [comment]
Ugh. I'd actually LOVE some help! First time handling pull requests.. Can you tell? :scream:

**Comment by Swoot1** [comment]
I fixed the conflict but it looks like the table-cell.js is very slim nowadays and doesn't need my fix ;) Maybe I'll do another pull request someday and hope for another merge conflict so that you can solve that one :D As David says the worst thing that can happen is nothing.

**Comment by as223jx** [comment]
@Swoot1 Thank, I really appreciate it! Haha, for sure, I need to understand this better. :smile:

**Pull request merged**
